### ISSUE TITLE
[Bug]: Create Extra: Crash when Multiplayer is clicked

### ISSUE THREAD

**Issue by vercte** [BondiBen/minecraft-modpacks#16]
### Contact Details

discord: @vercte

### What happened?

I just installed the newest version of Create Extra (1.5.1) and whenever I click on the Multiplayer option in the main menu, the game crashes. Singleplayer is fine, as well as all the other menu options.

### Version

Create-Extra (Default)

### In which os are you seeing the problem?

Windows 10/11

### Relevant log output

```shell
[12:17:55] [Render thread/WARN]: Mixin transformation of net.minecraft.class_4267$class_4270 failed
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:454) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:241) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:161) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:147) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239) ~[quilt-loader-0.23.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_4267.method_20131(class_4267.java:66) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4267.method_20125(class_4267.java:90) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_500.method_25426(class_500.java:77) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_437.method_25423(class_437.java:297) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_310.method_1507(class_310.java:1080) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_442.method_19860(class_442.java:167) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_442.method_25402(class_442.java:299) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[minecraft-1.20.1.i0:0/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:build 7]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_310.method_1523(class_310.java:1244) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.23.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.23.1.jar:?]
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector removeUpOnButton(Lnet/minecraft/class_332;Lnet/minecraft/class_2960;IIII)V in #draggable_lists:quilt-draggable_lists-common.mixins.json:server.MixinOnlineServerEntry from mod draggable_lists failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap quilt-draggable_lists-common-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	... 39 more
[12:17:55] [Render thread/INFO]: Stopping JEI
[12:17:55] [Render thread/INFO]: Stopping JEI
[12:17:55] [Render thread/INFO]: Sending Runtime Unavailable...
[12:17:55] [Render thread/INFO]: Stopping JEI GUI
[12:17:55] [Render thread/INFO]: Sending Runtime Unavailable took 479.1 ?s
[12:17:55] [Render thread/INFO]: [FANCYMENU] Registering MenuHandler for screen: net.minecraft.class_424
[12:17:55] [Render thread/INFO]: Clearing 'BetterStatsClientNetworkHandler' flags.
[12:17:55] [Render thread/INFO]: emissive suffixes loaded: {_e}.
[12:17:56] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:414) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[minecraft-1.20.1.i0:0/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:build 7]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_310.method_1523(class_310.java:1244) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.23.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.23.1.jar:?]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_4267$class_4270 failed
	at net.minecraft.class_4267.method_20131(class_4267.java:66) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4267.method_20125(class_4267.java:90) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_500.method_25426(class_500.java:77) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_437.method_25423(class_437.java:297) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_310.method_1507(class_310.java:1080) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_442.method_19860(class_442.java:167) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_442.method_25402(class_442.java:299) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[minecraft-1.20.1.i0:0/:?]
	... 18 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_4267$class_4270 failed
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:459) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:241) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:161) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:147) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239) ~[quilt-loader-0.23.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_4267.method_20131(class_4267.java:66) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4267.method_20125(class_4267.java:90) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_500.method_25426(class_500.java:77) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_437.method_25423(class_437.java:297) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_310.method_1507(class_310.java:1080) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_442.method_19860(class_442.java:167) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_442.method_25402(class_442.java:299) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[minecraft-1.20.1.i0:0/:?]
	... 18 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:454) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:241) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:161) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:147) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239) ~[quilt-loader-0.23.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_4267.method_20131(class_4267.java:66) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4267.method_20125(class_4267.java:90) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_500.method_25426(class_500.java:77) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_437.method_25423(class_437.java:297) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_310.method_1507(class_310.java:1080) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_442.method_19860(class_442.java:167) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_442.method_25402(class_442.java:299) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[minecraft-1.20.1.i0:0/:?]
	... 18 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector removeUpOnButton(Lnet/minecraft/class_332;Lnet/minecraft/class_2960;IIII)V in #draggable_lists:quilt-draggable_lists-common.mixins.json:server.MixinOnlineServerEntry from mod draggable_lists failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap quilt-draggable_lists-common-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:454) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:241) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:161) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:147) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239) ~[quilt-loader-0.23.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_4267.method_20131(class_4267.java:66) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4267.method_20125(class_4267.java:90) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_500.method_25426(class_500.java:77) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_437.method_25423(class_437.java:297) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_310.method_1507(class_310.java:1080) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_442.method_19860(class_442.java:167) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_442.method_25402(class_442.java:299) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[minecraft-1.20.1.i0:0/:?]
	... 18 more
[12:17:56] [Render thread/INFO]: [FastQuit] Exiting FastQuit.
```

**Comment by BondiBen** [comment]
this should be resolved with the latest version
